### ISSUE TITLE
typesの翻訳

### ISSUE THREAD

**Issue by ababup1192** [elm-jp/guide#26]
- [x]  [README.mdの翻訳](#27)
- [x]  [custom_types.mdの翻訳](#28)
- [x]  [pattern_matching.mdの翻訳](#29)
- [x]  [reading_types.mdの翻訳](#30)
- [x]  [type_aliases.mdの翻訳](#31)
