### ISSUE TITLE
appendixの翻訳

### ISSUE THREAD

**Issue by ababup1192** [elm-jp/guide#55]
- [x] [function_types.mdの翻訳](#56)
- [x] [types_as_bits.mdの翻訳](#57)
- [x] [types_as_sets.mdの翻訳](#58)

**Comment by km-tr** [comment]
@ababup1192 @arowM 
これを担当したいです
